name: LambdaTest Smoke Test add books to cart

on:
  workflow_dispatch:

jobs:
  run-test:

    runs-on: ubuntu-latest

    env:
      LT_USERNAME: ${{ secrets.LT_USERNAME }}
      LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install robotframework-jsonlibrary

      - name: Run Robot Test
        run: |
          robot --outputdir Test_Report TestCases/add_books_cart.robot   
          
    

      - name: Generate RobotMetrics Report
        run: |
          pip install robotframework-metrics
          robotmetrics -I Test_Report/output.xml          